- name: copy and run the files
  remote_user: ec2-user
  sudo: yes
  hosts: dockerswarm
  vars:
   ansible_ssh_private_key_file: "/home/ec2-user/Lab-2.pem"
  tasks:
   - name: run files
     copy:
      src: /home/ec2-user/deploy.yml
      dest: /root/
      mode: u=rwx,g=rwx,o=rwx
   - name: run files
     copy:
      src: /home/ec2-user/ani.yml
      dest: /root/
      mode: u=rwx,g=rwx,o=rwx
   - name: remove crules stacks
     command: docker stack rm pig
   - pause:
      seconds: 20
   - name: run files
     command: docker stack deploy --compose-file deploy.yml pig
