- name: copy and run the files
  remote_user: ec2-user
  sudo: yes
  hosts: dockerswarm
  vars:
   ansible_ssh_private_key_file: "/var/lib/jenkins/workspace/prem/Lab-2.pem"
  tasks:
   - name: follow my commands 
     command: docker stack rm pig
   - pause:
      seconds: 20
   - name: run files
     command: docker stack deploy --compose-file deploy.yml pig
